### ISSUE TITLE
base_cards_with_expansion option behaves differently

### ISSUE THREAD

**Issue by sumpfork** [sumpfork/bgtools_web#11]
For some reason, the online generator seems to default and insist on having the base cards in all expansions, while the command line script defaults to not having the base cards in expansions and needs an option specified to do so ... what's up?

@wvoigt - I don't know if you tested your PRs, but did you notice this?

**Comment by wvoigt** [comment]
A quick test showed that this happens with the command line script as well.  Almost as if the setting `--base_cards_with_expansion` is being set (when it is not).

**Comment by wvoigt** [comment]
So it "works" if you also select Base with the expansions.
I think this has to do with line 963 in main.py
```
    cardSorter = CardSorter(
        options.order,
        {card.card_tag: card.name for card in cards if card.cardset_tag.lower() == 'base'}) <-- here
```
The 2nd argument is passing a list of the base cards.  Now if the "Base" set is not included at this point in cards, then nothing will go into this list.  And if nothing is in this list, nothing matches this list to be removed from the expansion in  line 968:
```
    if options.base_cards_with_expansion:
        cards = [card for card in cards if card.cardset_tag.lower() != 'base']
    else:
        cards = [card for card in cards
                 if not cardSorter.isBaseExpansionCard(card)] <-- here
```

**Comment by wvoigt** [comment]
I created PR 181 to fix this.  
Note: when you *do* want the base cards with the expansion via `--base_cards_with_expansion` the base cards print at the back of the expansion, together.  They are not alphabetical with the rest of the cards.   I did not change that behavior there.   
Also, restating existing behavior, if you pick Base along with an expansion with `--base_cards_with_expansion` , a separate Base set is not printed.

**Comment by wvoigt** [comment]
After sleeping on this a bit, I think there is another way to do this:
```
    cardSorter = CardSorter(
        options.order,
        {card.card_tag: card.name for card in cards if card.cardset_tag.lower() == 'base'})
```
This is figuring out the base set "on the fly".  But the way it is checking things, it is only looking to see if the "base" set is included.  If the base set is not included, nothing will match here.

So instead of checking for `if card.cardset_tag.lower() == 'base'` instead it checks to see of there are any  "base" matches in card.cardset_tags.  I think at this point, each card will still carry it's original set information.
So cardset_tag has what this card's set is, but cardset_tags has all the sets it belongs to.  May have to expand it to a list and then check for membership in the list.

I'm going to be out a good part of the day, so I'm not going to be able to try this out quickly.  But I wanted to share in case others did have time.

**Comment by wvoigt** [comment]
@sumpfork 
I have a more simple fix in PR 182 at https://github.com/sumpfork/dominiontabs/pull/182
While this fixes a bug in the existing code, I think the actual intended logic needs to change.  Currently, if you select `--base_cards_with_expansion` you can never get a separate set of base cards.  They will always (and only) be included with the expansions that have base cards. 
I don't think that is intuitive from the web interface.  I think we should change it so that if they request the "Base" expansion, they get it, even if (down the road) they select an option to print the base cards as part of the expansions (Dominion and Intrigue).
If you agree, I can make that change too.

**Comment by wvoigt** [comment]
I updated PR 182 at sumpfork/dominiontabs#182 to print the base set if the base set is requested.  Even if `--base_cards_with_expansion` is also requested.  Now you get dividers for base cards in both places under those conditions.
